# SCA scan configuration for Fluid Attacks' standalone SCA scanner.
# See: https://help.fluidattacks.com/portal/en/kb/articles/use-standalone-scanners
namespace: thunderbird-ios
working_dir: /repo
language: EN
output:
  file_path: /repo/fluidscan-sca-results.sarif
  format: SARIF
sca:
  include:
    - .
  exclude:
    - glob(**/test/**)
    - glob(docs/**)
file_size_limit: false
tracing_opt_out: true
